version: "3.1"

services:
  kochbuch-db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  kochbuch-ws:
    image: sthomasch/kochbuch-sebastian
    restart: always
    ports:
      - 5000:5000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@kochbuch-db:27017/
      ME_CONFIG_BASICAUTH: false